services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - fromGroup: supabase-creds
    nota:

  - type: static
    name: qline-frontend
    Root Director: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    nota: primero limpiar el node_mobile y package lockjson, volver a crearlos
